languange: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
  - node_modules

install:
  - npm install
script:
  - npm test -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
  - npm run lint

deploy:
  provider: heroku
  api_key: $heroku_api_key
  app: sleepy-brushlands-50933
  on: master

