const MOCK_DATA = [{ date: "02/08/2018", description: "risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc", amount: -9012806 },
    { date: "02/02/2018", description: "luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac", amount: -7900765 },
    { date: "02/05/2018", description: "sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst", amount: 6510601 },
    { date: "02/22/2018", description: "quis justo maecenas rhoncus aliquam lacus morbi quis tortor id", amount: -3164124 },
    { date: "01/26/2018", description: "phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac", amount: 7583913 },
    { date: "02/08/2018", description: "mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere", amount: 2200983 },
    { date: "02/01/2018", description: "quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas", amount: 1405046 },
    { date: "02/24/2018", description: "justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus", amount: -3258577 },
    { date: "02/02/2018", description: "est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum", amount: -2960089 },
    { date: "02/19/2018", description: "vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum", amount: 3518029 },
    { date: "02/19/2018", description: "duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat", amount: 9829481 },
    { date: "02/23/2018", description: "faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec", amount: 94787 },
    { date: "02/07/2018", description: "aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis", amount: 5894960 },
    { date: "02/16/2018", description: "elementum in hac habitasse platea dictumst morbi vestibulum velit id", amount: -9952219 },
    { date: "02/21/2018", description: "sit amet eleifend pede libero quis orci nullam molestie nibh in", amount: -4005683 },
    { date: "02/10/2018", description: "quam sapien varius ut blandit non interdum in ante vestibulum ante", amount: -6519748 },
    { date: "02/12/2018", description: "vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra", amount: -6699 },
    { date: "02/06/2018", description: "consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum", amount: 9398554 },
    { date: "02/09/2018", description: "nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at", amount: 4539254 },
    { date: "01/30/2018", description: "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia", amount: -3930880 },
    { date: "02/05/2018", description: "nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac", amount: 3263439 },
    { date: "02/03/2018", description: "felis fusce posuere felis sed lacus morbi sem mauris laoreet ut", amount: -7866428 },
    { date: "02/13/2018", description: "felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl", amount: 2919652 },
    { date: "02/03/2018", description: "habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem", amount: -5876235 },
    { date: "01/31/2018", description: "posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor", amount: 4067062 },
    { date: "02/08/2018", description: "pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse", amount: -2633851 },
    { date: "02/03/2018", description: "amet nulla quisque arcu libero rutrum ac lobortis vel dapibus", amount: 3498635 },
    { date: "01/29/2018", description: "feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea", amount: -6909807 },
    { date: "02/10/2018", description: "sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris", amount: -4450652 },
    { date: "02/17/2018", description: "et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin", amount: 3048291 },
    { date: "02/10/2018", description: "rutrum nulla nunc purus phasellus in felis donec semper sapien a", amount: 7381707 },
    { date: "02/18/2018", description: "congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui", amount: 1588608 },
    { date: "02/14/2018", description: "nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac", amount: -355351 },
    { date: "01/25/2018", description: "et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor", amount: -6411216 },
    { date: "01/30/2018", description: "augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra", amount: 8234829 },
    { date: "02/22/2018", description: "platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum", amount: -5916006 },
    { date: "02/24/2018", description: "libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc", amount: 1555660 },
    { date: "02/19/2018", description: "aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent", amount: -2105760 },
    { date: "02/11/2018", description: "eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies", amount: -3609015 },
    { date: "01/30/2018", description: "sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac", amount: 2670933 },
    { date: "02/17/2018", description: "nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer", amount: -7762322 },
    { date: "02/24/2018", description: "quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan", amount: -4551505 },
    { date: "02/14/2018", description: "lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque", amount: -876426 },
    { date: "01/27/2018", description: "dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo", amount: -983249 },
    { date: "01/29/2018", description: "diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus", amount: 2144164 },
    { date: "02/01/2018", description: "volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus", amount: -2409399 },
    { date: "02/11/2018", description: "ut ultrices vel augue vestibulum ante ipsum primis in faucibus", amount: 1681287 },
    { date: "02/17/2018", description: "mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris", amount: -532184 },
    { date: "02/05/2018", description: "in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque", amount: -8329738 },
    { date: "02/23/2018", description: "purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur", amount: 9254051 },
    { date: "02/01/2018", description: "neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet", amount: -5583304 },
    { date: "02/18/2018", description: "magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus", amount: -8368168 },
    { date: "02/01/2018", description: "faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur", amount: 1702663 },
    { date: "01/29/2018", description: "aliquam quis turpis eget elit sodales scelerisque mauris sit amet", amount: -3009408 },
    { date: "01/28/2018", description: "posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui", amount: -8662334 },
    { date: "02/02/2018", description: "ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing", amount: 907470 },
    { date: "02/07/2018", description: "dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et", amount: -1715206 },
    { date: "02/02/2018", description: "orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum", amount: -8753031 },
    { date: "02/16/2018", description: "posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna", amount: 2674601 },
    { date: "02/01/2018", description: "aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo", amount: -1266210 },
    { date: "02/04/2018", description: "est phasellus sit amet erat nulla tempus vivamus in felis eu sapien", amount: 4921931 },
    { date: "02/10/2018", description: "in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis", amount: 3019695 },
    { date: "02/17/2018", description: "in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis", amount: 5850956 },
    { date: "02/12/2018", description: "enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet", amount: -7609340 },
    { date: "02/17/2018", description: "lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi", amount: 6734105 },
    { date: "02/07/2018", description: "ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede", amount: -5501785 },
    { date: "02/07/2018", description: "purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus", amount: -3468845 },
    { date: "02/17/2018", description: "lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis", amount: 5599897 },
    { date: "02/12/2018", description: "curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et", amount: 9821266 },
    { date: "02/01/2018", description: "platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat", amount: -797183 },
    { date: "02/10/2018", description: "nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam", amount: -8945623 },
    { date: "02/15/2018", description: "praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla", amount: 586740 },
    { date: "01/27/2018", description: "maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum", amount: -6454129 },
    { date: "02/04/2018", description: "ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper", amount: 4919860 },
    { date: "01/31/2018", description: "nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet", amount: 5909390 },
    { date: "02/08/2018", description: "et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin", amount: -1873934 },
    { date: "02/07/2018", description: "curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi", amount: -4720631 },
    { date: "02/01/2018", description: "maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat", amount: 8078678 },
    { date: "02/14/2018", description: "consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere", amount: 9095040 },
    { date: "02/04/2018", description: "odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet", amount: -8157148 },
    { date: "02/07/2018", description: "porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper", amount: -1321343 },
    { date: "01/25/2018", description: "luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et", amount: 9421904 },
    { date: "02/05/2018", description: "vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium", amount: 8005133 },
    { date: "02/15/2018", description: "sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis", amount: -4934879 },
    { date: "02/03/2018", description: "vel est donec odio justo sollicitudin ut suscipit a feugiat et", amount: 8712119 },
    { date: "01/30/2018", description: "placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris", amount: -2232498 },
    { date: "02/06/2018", description: "eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam", amount: -3802732 },
    { date: "01/31/2018", description: "in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla", amount: 6844272 },
    { date: "01/27/2018", description: "etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id", amount: -447526 },
    { date: "01/31/2018", description: "duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa", amount: -5610624 },
    { date: "02/18/2018", description: "elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus", amount: -8575838 },
    { date: "02/13/2018", description: "sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices", amount: 6569734 },
    { date: "02/04/2018", description: "ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget", amount: -8599575 },
    { date: "02/02/2018", description: "et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec", amount: -8128918 },
    { date: "02/06/2018", description: "ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer", amount: 9367610 },
    { date: "02/12/2018", description: "auctor gravida sem praesent id massa id nisl venenatis lacinia aenean", amount: 8172742 },
    { date: "02/09/2018", description: "vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur", amount: -295191 },
    { date: "02/18/2018", description: "semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique", amount: -4926175 },
    { date: "02/11/2018", description: "justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem", amount: 7014313 },
    { date: "01/29/2018", description: "odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non", amount: 6071915 }];

export default MOCK_DATA;
